### ISSUE TITLE
[Feat] 문의/등록 메인 뷰 구현

### ISSUE THREAD

**Issue by FpRaArNkK** [GachonRookie/iOS#13]
# 📝 작업 내용
문의/등록 탭의 메인 뷰를 구현합니다.

## ✔️ To-Do
- [x] 상단  세그먼트 컨트롤 추가
- [x] 동아리 리스트 CollectionViewCell 작업
- [x] 동아리 리스트 3개 CollecitonView 추가, 연결

# 👀 ETC (추후 개발해야 할 것, 참고자료 등)
