### ISSUE TITLE
[Feat] 온보딩 및 메인 탭바 컨트롤러 구현

### ISSUE THREAD

**Issue by youz2me** [GachonRookie/iOS#2]
# 📝 작업 내용
- 스플래시 화면을 구현합니다.
- 온보딩 화면 UI를 수정합니다.
- 메인 탭바를 구현합니다.
- `feature/2-base-ui` 브랜치에서 작업합니다.

## ✔️ To-Do
- [x] 스플래시 화면 구현
- [x] 온보딩 화면 UI 수정
- [x] 메인 탭바 구현
- [x] 화면 전환 구현

# 👀 ETC (추후 개발해야 할 것, 참고자료 등)
